name: Update Dataset Citations Manually

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update_citations_job:
    runs-on: ubuntu-latest
    name: Discover Datasets & Update Citations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Discover relevant datasets
        id: discover
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Or a specific PAT if needed for cross-repo access not covered by GITHUB_TOKEN
        run: |
          python discover_datasets.py --output-file discovered_datasets.txt
          echo "dataset_list_file=discovered_datasets.txt" >> $GITHUB_OUTPUT

      - name: Update citation information
        env:
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
        run: |
          python update_citations.py \
            --dataset-list-file ${{ steps.discover.outputs.dataset_list_file }} \
            --previous-citations-file citations/previous_citations.csv \
            --output-dir citations_output/
          # Add steps here to commit and push changes, or create a PR
          # This will be handled in a later task (Task 4 & 5) 